import type { I11n } from './i11n';
import zhCN from './zh-CN';

const lang: I11n = {
	...zhCN,
	frontend: {
		settings: {
			title: 'Settings',
			language: 'Language',
			dataRadix: 'Data size units',
			colorTheme: 'Color theme',
			taskListPerformance: 'Task list performance',
			light: 'Light',
			dark: 'Dark',
			system: 'Follow system',
			enableVirtualTaskList: 'Virtual list (strong optimization)',
			fullRenderTaskList: 'Full rendering (lighter optimization)',
			useVirtualTaskListDesc: 'This renders tasks outside the viewport in a lighter form to improve performance in large queues.\nIt is much faster with hundreds of tasks, but fast scrolling may briefly show blank rows and rare refresh spikes.\nIf you usually work with fewer than 50 tasks, full rendering is recommended.',
		},
		about: {
			title: 'About',
			philosophyTitle: 'The Komorebi Idea',
			philosophyBody: [
				'Simple: fold complex FFmpeg options into practical workflows so users do not have to become encoding specialists first.',
				'Efficient: choose sensible conversion paths by default while keeping progress, logs, and batch queues clear and controllable.',
				'Automated: let the app handle what it can infer, including container compatibility, presets, NCM batches, and common output naming.',
				'Komorebi is meant to sit quietly in the background: less friction, faster media conversion, and fewer decisions that do not need to be manual.',
			],
			creditsTitle: 'Credits',
			credits: [
				{ name: 'FFBox', url: 'https://github.com/ttqftech/FFBox', description: 'Komorebi is adapted from FFBox 5.x and reworks its task, parameter, and local service systems.' },
				{ name: 'FFmpeg', url: 'https://ffmpeg.org/', description: 'Provides the core media decoding, encoding, remuxing, and probing capabilities.' },
				{ name: 'ncmdump', url: 'https://github.com/taurusxin/ncmdump', description: 'Provides NCM file conversion support.' },
			],
		},
		menuCenter: {
			settings: 'Settings',
			about: 'About',
		},
		appMenu: {
			showEnvironmentInfo: 'Show environment info',
			sourceNotice: 'Source notice',
			ffboxProject: 'FFBox project',
			ncmdumpProject: 'ncmdump project',
			ffmpegProject: 'FFmpeg project',
			exit: 'Exit Komorebi',
			tasks: 'Tasks (T)',
			addTasksFromFiles: 'Add tasks from files',
			addTasksFromFilesTip: 'Choose files and add them to the current workflow queue',
			addTasksFromText: 'Add tasks from text',
			addTasksFromTextTip: 'Enter one file or folder path per line',
			allTaskActions: 'All task actions',
			stop: 'Stop',
			deleteFinished: 'Delete finished',
			deleteIdle: 'Delete idle',
			resetErrors: 'Reset failed tasks',
			selectedTaskActions: 'Selected task actions',
			startNow: 'Start now',
			queueStartSelected: 'Queue start',
			stopOrReset: 'Stop or reset',
			delete: 'Delete',
			startQueue: 'Start queue',
			pauseQueue: 'Pause queue',
			view: 'View (V)',
			zoomIn: 'Zoom in',
			zoomOut: 'Zoom out',
			resetZoom: 'Reset zoom',
			infoCenter: 'Info center',
			transferCenter: 'Transfer center',
			menuCenter: 'Menu center',
			stoppedTasks: (count) => `Stopped ${count} task(s)`,
			deletedTasks: (count) => `Deleted ${count} task(s)`,
			resetTasks: (count) => `Reset ${count} task(s)`,
		},
		dialogs: {
			exitTitle: 'Exit now?',
			exitContent: (count) => `The local server still has ${count} unfinished task(s).\nIf Komorebi started the service, exiting will force those tasks to stop.`,
			exitConfirm: 'Exit',
			exitCancel: 'Wait',
			welcome: (version) => `Welcome to Komorebi ${version}`,
		},
		ffmpegGuide: {
			checkingTitle: 'Checking FFmpeg',
			checkingText: 'Reading the FFmpeg bundled with the installer. Please wait.',
			missingTitle: 'FFmpeg dependency missing',
			missingTip: 'Please follow these steps:',
			stepDownload: 'Download FFmpeg for',
			stepWindowsPath: 'Option 1: add the folder containing ffmpeg to PATH',
			stepUnixPath: 'Option 1: put the ffmpeg executable into /usr/local/bin',
			stepSameDir: 'Option 2: put the ffmpeg executable next to the Komorebi executable',
			stepMacDir: (path) => `Option 2: put the ffmpeg executable into ${path}`,
			restart: (target) => `Restart ${target} after completing the steps above.`,
			currentOs: 'your operating system',
		},
		dragDrop: {
			ncmInputs: (prefix, count) => `${prefix}${count} NCM input(s)`,
			inputs: (prefix, count, mode) => `${prefix}${count} ${mode === 'multiInput' ? 'input path(s)' : 'separate task(s)'}`,
			textPaths: 'Text path ',
			createTask: 'Drop files, folders, or text here to create tasks',
			batchTaskMode: 'Batch task mode',
			multiInputMode: 'Multi-input task mode',
			fastStart: 'Start after drop',
			status: (enabled) => `Status: ${enabled ? 'enabled' : 'off'}`,
		},
		komorebi: {
			workflows: {
				videoCompress: 'Video compression',
				audioConvert: 'Audio conversion',
				remux: 'Remux',
				ncm: 'NCM conversion',
			},
			hints: {
				noInput: 'Choose or drop files, and Komorebi will detect available formats automatically.',
				hasVideoAudio: 'Video and audio streams detected. Incompatible options are disabled.',
				hasVideo: 'Video stream detected. Options unsuitable for audio conversion are disabled.',
				hasAudio: 'Audio stream detected. Options unsuitable for video packaging are disabled.',
				unknown: 'No convertible media stream has been detected yet.',
			},
			fields: {
				scene: 'Scene',
				encoder: 'Encoder',
				quality: 'Quality',
				container: 'Container',
				audioTrack: 'Audio track',
				externalAudio: 'External audio',
				externalAudioFile: 'External audio file',
				outputDir: 'Output folder',
				outputName: 'Output name',
				targetFormat: 'Target format',
				targetContainer: 'Target container',
				qualityPreset: 'Quality preset',
				convertFormat: 'Convert format',
			},
			options: {
				sceneAnime: 'Anime / 2D',
				sceneScreen: 'Screen / game',
				sceneLive: 'Live action / film',
				qualityHigh: 'High quality',
				qualityBalanced: 'Balanced',
				qualitySmall: 'Small size',
				qualityTiny: 'Tiny size',
				keepSourceAudio: 'Keep source audio',
				muteVideo: 'Muted video',
				useExternalAudio: 'Use external audio',
				noExternalAudio: 'Do not add external audio',
				addExternalAudio: 'Add external audio',
				audioLossless320: '320k / lossless',
				audio192: '192k',
				audio128: '128k',
				audio64: '64k',
				ncmAuto: 'Auto from source music',
				ncmCopy: 'Decrypt only, no compression',
				ncmStandard: 'Standard compression',
				ncmSmall: 'Small-size compression',
				recursive: 'Recursive folders',
				deleteSource: 'Delete source after success',
			},
			placeholders: {
				externalAudio: 'C:/Music/audio.flac',
				outputToSourceDir: 'Leave empty to output beside the source file',
				outputToSourceRoot: 'Leave empty to output to the source folder',
				videoOutputName: 'Default when empty: [filename]_komorebi',
				audioOutputName: 'Default when empty: [filename]_audio',
				remuxOutputName: 'Default when empty: [filename]_remux',
				ncmOutputName: 'Leave empty to use the ncmdump default name',
			},
			estimate: {
				waiting: 'Select a video task to show estimated size and compression ratio',
				unknown: 'This task is missing duration or bitrate data, so the compression ratio cannot be estimated yet',
				summary: (output, source, ratioText) => `Estimated output ${output}, source about ${source}, ${ratioText}`,
				actualSummary: (output, source, ratioText) => `Actual output ${output}, source ${source}, ${ratioText}`,
				shrink: (rate) => `compression about ${rate}%`,
				grow: (rate) => `estimated growth ${rate}%`,
				flat: 'size is roughly unchanged',
				actualShrink: (rate) => `actual compression ${rate}%`,
				actualGrow: (rate) => `actual growth ${rate}%`,
				actualFlat: 'size is roughly unchanged',
			},
			notes: {
				remux: 'Streams are copied by default, keeping subtitles and metadata. If the container is incompatible, Komorebi retries with high-fidelity transcoding.',
				ncm: 'Drop .ncm files or folders into the task area above. Folders are expanded into individual NCM tasks.',
			},
			actions: {
				choose: 'Choose',
				setGlobal: 'Set as global parameters',
				applySelected: 'Apply to selected tasks',
			},
		},
		applicationMenu: {
			编辑: 'Edit',
			撤销: 'Undo',
			重做: 'Redo',
			剪切: 'Cut',
			复制: 'Copy',
			粘贴: 'Paste',
			删除: 'Delete',
			全选: 'Select all',
		},
	},
};

export default lang;
