import type { I11n } from './i11n';
import zhCN from './zh-CN';

const lang: I11n = {
	...zhCN,
	frontend: {
		settings: {
			title: '設定',
			language: '表示言語',
			dataRadix: 'データ容量の単位',
			colorTheme: 'カラーテーマ',
			animationSpeed: 'アニメーション速度',
			taskListPerformance: 'タスクリストの最適化',
			light: 'ライト',
			dark: 'ダーク',
			system: 'システムに合わせる',
			animationDefault: '標準',
			animationFast: '速い',
			animationSlow: '遅い',
			enableVirtualTaskList: '仮想リストを有効化（強い最適化）',
			fullRenderTaskList: '完全描画（軽い最適化）',
			useVirtualTaskListDesc: '画面外のタスクを軽量表示に切り替え、大量のタスクで描画性能を高めます。\n数百件のタスクでは反応が大きく改善しますが、高速スクロール時に一瞬空白が出たり、まれに CPU 使用率が上がる場合があります。\n通常 50 件未満のタスクしか扱わない場合は、完全描画をおすすめします。',
		},
		about: {
			title: 'Komorebi について',
			philosophyTitle: 'Komorebi の理念',
			philosophyBody: [
				'シンプル：複雑な FFmpeg の設定を日常的なワークフローにまとめ、専門知識なしでも使えるようにします。',
				'高効率：安全な変換経路を既定で選びつつ、進捗、ログ、バッチキューを見やすく保ちます。',
				'自動化：コンテナ互換性、プリセット、NCM の一括処理、出力名など、判断できることはソフトウェアに任せます。',
				'Komorebi は木漏れ日のように静かに寄り添うツールを目指しています。余計な手間を減らし、変換を少し軽く、速く、確実にします。',
			],
			creditsTitle: '使用プロジェクト',
			credits: [
				{ name: 'FFBox', url: 'https://github.com/ttqftech/FFBox', description: 'Komorebi は FFBox 5.x をベースに、タスク、パラメータ、ローカルサービスを調整しています。' },
				{ name: 'FFmpeg', url: 'https://ffmpeg.org/', description: '音声・映像のデコード、エンコード、リマックス、解析機能を提供します。' },
				{ name: 'ncmdump', url: 'https://github.com/taurusxin/ncmdump', description: 'NCM ファイル変換機能を提供します。' },
			],
		},
		menuCenter: {
			settings: '設定',
			about: '概要',
		},
		appMenu: {
			showEnvironmentInfo: '環境情報を表示',
			sourceNotice: 'ソース表記',
			ffboxProject: 'FFBox プロジェクト',
			ncmdumpProject: 'ncmdump プロジェクト',
			ffmpegProject: 'FFmpeg プロジェクト',
			exit: 'Komorebi を終了',
			tasks: 'タスク (T)',
			addTasksFromFiles: 'ファイルからタスクを追加',
			addTasksFromFilesTip: 'ファイルを選択して現在のワークフローに追加します',
			addTasksFromText: 'テキストからタスクを追加',
			addTasksFromTextTip: '1 行に 1 つのファイルまたはフォルダパスを入力します',
			allTaskActions: '全タスク操作',
			stop: '停止',
			deleteFinished: '完了済みを削除',
			deleteIdle: '未開始を削除',
			resetErrors: 'エラーをリセット',
			selectedTaskActions: '選択中のタスク操作',
			startNow: '今すぐ開始',
			queueStartSelected: 'キューに入れて開始',
			stopOrReset: '停止またはリセット',
			delete: '削除',
			startQueue: 'キューを開始',
			pauseQueue: 'キューを一時停止',
			view: '表示 (V)',
			zoomIn: '拡大',
			zoomOut: '縮小',
			resetZoom: 'ズームをリセット',
			infoCenter: '通知センター',
			transferCenter: '転送センター',
			menuCenter: 'メニューセンター',
			stoppedTasks: (count) => `${count} 件のタスクを停止しました`,
			deletedTasks: (count) => `${count} 件のタスクを削除しました`,
			resetTasks: (count) => `${count} 件のタスクをリセットしました`,
		},
		dialogs: {
			exitTitle: '終了しますか？',
			exitContent: (count) => `ローカルサーバーに未完了のタスクが ${count} 件あります。\nKomorebi がサービスを起動した場合、終了するとタスクは強制停止されます。`,
			exitConfirm: '終了',
			exitCancel: '待つ',
			welcome: (version) => `Komorebi ${version} へようこそ`,
		},
		ffmpegGuide: {
			checkingTitle: 'FFmpeg を確認中',
			checkingText: 'インストーラーに含まれる FFmpeg を読み込んでいます。しばらくお待ちください。',
			missingTitle: 'FFmpeg が見つかりません',
			missingTip: '以下の手順を確認してください：',
			stepDownload: 'FFmpeg 公式サイトから、次の環境向けのファイルをダウンロード：',
			stepWindowsPath: '方法 1：ffmpeg 実行ファイルのあるフォルダを PATH に追加する',
			stepUnixPath: '方法 1：ffmpeg 実行ファイルを /usr/local/bin に置く',
			stepSameDir: '方法 2：ffmpeg 実行ファイルを Komorebi 実行ファイルと同じフォルダに置く',
			stepMacDir: (path) => `方法 2：ffmpeg 実行ファイルを ${path} に置く`,
			restart: (target) => `上記の操作後、${target}を再起動すると使用できます`,
			currentOs: '現在の OS',
		},
		dragDrop: {
			ncmInputs: (prefix, count) => `${prefix}${count} 件の NCM 入力`,
			inputs: (prefix, count, mode) => `${prefix}${count} 件の${mode === 'multiInput' ? '入力パス' : '個別タスク'}`,
			textPaths: 'テキストパス',
			createTask: 'ファイル、フォルダ、テキストをここにドロップしてタスクを作成',
			batchTaskMode: '一括タスク追加モード',
			multiInputMode: '複数入力 1 タスクモード',
			fastStart: 'ドロップ後すぐ開始',
			status: (enabled) => `状態：${enabled ? '有効' : 'オフ'}`,
		},
		komorebi: {
			workflows: {
				videoCompress: '動画圧縮',
				audioConvert: '音声変換',
				remux: 'リマックス',
				ncm: 'NCM 変換',
			},
			hints: {
				noInput: 'ファイルを選択またはドロップすると、Komorebi が利用可能な形式を自動検出します。',
				hasVideoAudio: '動画と音声ストリームを検出しました。非対応の形式は無効化されています。',
				hasVideo: '動画ストリームを検出しました。音声変換に適さない項目は無効化されています。',
				hasAudio: '音声ストリームを検出しました。動画コンテナに適さない項目は無効化されています。',
				unknown: '変換可能なメディアストリームはまだ検出されていません。',
			},
			fields: {
				scene: 'シーン',
				encoder: 'エンコーダー',
				quality: '品質',
				container: 'コンテナ',
				aspectRatio: '画面比率',
				resolution: '出力解像度',
				frameRate: '出力フレームレート',
				gifFps: 'GIF フレームレート',
				encodeSpeed: '変換速度',
				audioTrack: '音声トラック',
				externalAudio: '外部音声',
				externalAudioFile: '外部音声ファイル',
				outputDir: '出力フォルダ',
				outputName: '出力ファイル名',
				targetFormat: '目標形式',
				targetContainer: '目標コンテナ',
				qualityPreset: '品質プリセット',
				convertFormat: '変換形式',
			},
			options: {
				sceneAnime: 'アニメ / 二次元',
				sceneScreen: '画面録画 / ゲーム',
				sceneLive: '撮影',
				qualityHigh: '高品質',
				qualityBalanced: 'バランス',
				qualitySmall: '小容量',
				qualityTiny: '極小容量',
				aspectSource: '元の比率',
				aspectStandard: '標準',
				resolutionSource: '元の解像度',
				resolutionAboveSource: (resolution: string) => `元の ${resolution} を超過`,
				resolutionReadingSource: '元の解像度を読み取り中',
				frameRateSource: '元のフレームレート',
				frameRateAuto: '自動',
				frameRateLimited: (fps: number) => `実際 ${fps} FPS`,
				frameRateAboveSource: (fps: string) => `元の ${fps} FPS を超過`,
				gifFpsAuto: '自動',
				gifFpsLimited: (fps: number) => `実際 ${fps} FPS`,
				encodeSpeedFast: '高速',
				encodeSpeedBalanced: 'バランス',
				encodeSpeedLow: '低負荷',
				keepSourceAudio: '元の音声を保持',
				muteVideo: '無音動画',
				useExternalAudio: '外部音声を使用',
				noExternalAudio: '外部音声を追加しない',
				addExternalAudio: '外部音声を追加',
				audioLossless320: '320k / ロスレス',
				audio192: '192k',
				audio128: '128k',
				audio64: '64k',
				ncmAuto: '元の音楽に合わせて自動出力',
				ncmCopy: '復号のみ、圧縮しない',
				ncmStandard: '標準圧縮',
				ncmSmall: '小容量圧縮',
				recursive: 'フォルダを再帰処理',
				deleteSource: '成功後に元ファイルを削除',
			},
			placeholders: {
				externalAudio: 'C:/Music/audio.flac',
				outputToSourceDir: '空欄の場合は元ファイルのフォルダへ出力',
				outputToSourceRoot: '空欄の場合は元フォルダへ出力',
				videoOutputName: '空欄時の既定：[filename]_komorebi',
				audioOutputName: '空欄時の既定：[filename]_audio',
				remuxOutputName: '空欄時の既定：[filename]_remux',
				ncmOutputName: '空欄の場合は ncmdump の既定名を使用',
			},
			estimate: {
				waiting: '動画タスクを選択すると、推定出力サイズと圧縮率を表示します',
				unknown: 'このタスクは時間またはビットレート情報が不足しているため、圧縮率をまだ推定できません',
				summary: (output, source, ratioText) => `推定出力 ${output}、元ファイル約 ${source}、${ratioText}`,
				actualSummary: (output, source, ratioText) => `実際の出力 ${output}、元ファイル ${source}、${ratioText}`,
				shrink: (rate) => `圧縮率約 ${rate}%`,
				grow: (rate) => `推定増加 ${rate}%`,
				flat: '容量はほぼ同じです',
				actualShrink: (rate) => `実際の圧縮率 ${rate}%`,
				actualGrow: (rate) => `実際の増加 ${rate}%`,
				actualFlat: '容量はほぼ同じです',
			},
			notes: {
				remux: '既定ではストリームをコピーし、字幕とメタデータを保持します。コンテナ非対応の場合は高忠実度の変換で再試行します。',
				ncm: '上のタスク領域へ .ncm ファイルまたはフォルダをドロップしてください。フォルダは個別の NCM タスクに展開されます。',
			},
			actions: {
				choose: '選択',
				setGlobal: 'グローバル設定にする',
				applySelected: '選択中のタスクに適用',
			},
		},
		applicationMenu: {
			编辑: '編集',
			撤销: '元に戻す',
			重做: 'やり直す',
			剪切: '切り取り',
			复制: 'コピー',
			粘贴: '貼り付け',
			删除: '削除',
			全选: 'すべて選択',
		},
	},
};

export default lang;
