import type { I11n } from './i11n';

const lang: I11n = {
	service: {
		功能限制_暂停转码: (taskName, byFrontend, reason) =>
			`任务「${taskName}」转码达到${byFrontend ? '前端' : '后端'}的${reason === 'media' ? '媒体时长' : '处理耗时'}时长上限了\n` +
			'🤫开发者设计该项限制的意图是为了给“伸手党”和“白嫖党”制造一些不便😞谁知盘中餐，粒粒皆辛苦！\n' +
			'☺️探访一下 FFBox 官网、作者发布媒介，或者 AI，或许就能发现激活方式了✅',
		功能限制_不能继续: (taskName, byFrontend, reason, pid) =>
			`任务「${taskName}」转码达到${byFrontend ? '前端' : '后端'}的${reason === 'media' ? '媒体时长' : '处理耗时'}时长上限了\n` +
			'请在菜单中心的功能解限面板查看详情\n' +
			`您可以选择停止该任务、激活${byFrontend ? '前端' : '后端'}后重试，或改用 FFBox 以外的软件恢复进程。PID：${pid}`,
		功能限制_任务数上限: (maxTaskCount, byFrontend) =>
			`😞任务数量达到${byFrontend ? '前端' : '后端'}上限了\n` +
			`💔您的用户等级最高支持在任务列表中放入 ${maxTaskCount} 个任务，您可以先删除一些任务再添加\n` +
			'🤫开发者设计该项限制的意图是避免超出合理范围的操作导致前端卡顿，\n' +
			'　并给“伸手党”和“白嫖党”制造一些不便😞谁知盘中餐，粒粒皆辛苦！\n' +
			'☺️探访一下 FFBox 官网、作者发布媒介，或者 AI，或许就能发现激活方式了✅',
		功能限制_滤镜图节点数上限: (maxNodeCount) => 
			`😞节点数量达到上限了\n` +
			`💔您的用户等级最高支持在滤镜图中放入 ${maxNodeCount} 个任务，您可以先删除一些节点再添加\n` +
			'☺️探访一下 FFBox 官网、作者发布媒介，或者 AI，或许就能发现激活方式了✅',
		},
	ffmpeg: {
		文件不存在: '输入文件不存在',
		内存或显存不足: '内存或显存不足',
		无硬件解码设备_nvenc: '没有可用的 NVIDIA 硬件编码设备',
		硬件解码错误回退软件_nvenc: '硬件解码器发生错误，将使用软件解码',
		硬件编码器不存在: 'ffmpeg 不认识所选的硬件解码器',
		硬件编码器初始化失败_amd: 'AMD 编码器初始化失败',
		复用器不支持某编码: (codecName) => `复用器（容器/格式）不支持搭配“${codecName}”编码，请尝试更换二者的搭配`,
		编码无法识别: '输入文件中的某些编码无法识别',
		移动文件信息到文件头: '正在移动文件信息到文件头',
		编码器输出参数设置有误: '编码器初始化失败，可能是输出参数设置有误',
		输入文件无法识别: '输入文件无法识别',
		权限不足: '权限不足',
		外存已满: '外存已满',
		无法原地编辑: 'ffmpeg 无法原地编辑文件，请考虑更改输出路径（文件夹或文件名）',
	},
	frontend: {
		settings: {
			title: '设置',
			language: '界面语言',
			dataRadix: '数据量进制和词头',
			colorTheme: '颜色主题',
			animationSpeed: '动画速度',
			taskListPerformance: '任务列表性能优化',
			light: '浅色',
			dark: '深色',
			system: '跟随系统',
			animationDefault: '默认',
			animationFast: '快速',
			animationSlow: '慢速',
			enableVirtualTaskList: '启用虚拟列表（强优化）',
			fullRenderTaskList: '完整渲染（弱优化）',
			useVirtualTaskListDesc: '该技术是将任务列表中滚动到画面外的任务项更改为超简渲染，从而在部分情况下提升渲染性能\n启用此优化后，任务数量过百时，整个界面的响应性能相比不优化有显著的性能提升，但快速滚动列表时会出现短暂的空白，且有概率出现渲染持续刷新导致高 CPU 占用的情况\n如您较少需要 50 个以上的任务，建议关闭此优化',
		},
		about: {
			title: '关于',
			philosophyTitle: 'Komorebi 的理念',
			philosophyBody: [
				'简单：把复杂的 FFmpeg 参数折叠成清晰的日常场景，让用户不必先成为编码专家。',
				'高效：默认选择稳妥的转换路径，保留进度、日志和批量队列，让一次处理很多文件也保持可控。',
				'自动化：能自动判断的事情交给软件完成，包括容器兼容、格式预设、NCM 批量处理和常用输出命名。',
				'Komorebi 希望像树影一样安静地存在：不抢走注意力，只把媒体转换这件事变得轻一点、快一点、可靠一点。',
			],
			creditsTitle: '引用与致谢',
			credits: [
				{ name: 'FFBox', url: 'https://github.com/ttqftech/FFBox', description: 'Komorebi 基于 FFBox 5.x 改造，继承并调整了任务、参数与本地服务体系。' },
				{ name: 'FFmpeg', url: 'https://ffmpeg.org/', description: '提供核心音视频解码、编码、转封装与分析能力。' },
				{ name: 'ncmdump', url: 'https://github.com/taurusxin/ncmdump', description: '提供 NCM 文件转换能力。' },
			],
		},
		menuCenter: {
			settings: '设置',
			about: '关于',
		},
		appMenu: {
			showEnvironmentInfo: '显示环境信息',
			sourceNotice: '来源声明',
			ffboxProject: 'FFBox 项目',
			ncmdumpProject: 'ncmdump 项目',
			ffmpegProject: 'FFmpeg 项目',
			exit: '退出 Komorebi',
			tasks: '任务 (T)',
			addTasksFromFiles: '添加任务（选择文件）',
			addTasksFromFilesTip: '选择文件并加入当前功能队列',
			addTasksFromText: '添加任务（从文本）',
			addTasksFromTextTip: '输入每行一个文件或目录路径',
			allTaskActions: '所有任务操作',
			stop: '停止',
			deleteFinished: '删除已完成',
			deleteIdle: '删除未启动',
			resetErrors: '重置出错任务',
			selectedTaskActions: '选中任务操作',
			startNow: '立即开始',
			queueStartSelected: '排队开始',
			stopOrReset: '停止或重置',
			delete: '删除',
			startQueue: '开始执行队列',
			pauseQueue: '暂停执行队列',
			view: '视图 (V)',
			zoomIn: '放大',
			zoomOut: '缩小',
			resetZoom: '重置缩放',
			infoCenter: '通知中心',
			transferCenter: '传输中心',
			menuCenter: '菜单中心',
			stoppedTasks: (count) => `已停止 ${count} 个任务`,
			deletedTasks: (count) => `已删除 ${count} 个任务`,
			resetTasks: (count) => `已重置 ${count} 个任务`,
		},
		dialogs: {
			exitTitle: '要退出吗？',
			exitContent: (count) => `本地服务器还有 ${count} 个任务未完成\n如果 Komorebi 服务是由客户端启动的，退出将会强制停止任务哦～`,
			exitConfirm: '退退退',
			exitCancel: '再等等',
			welcome: (version) => `欢迎使用 Komorebi ${version}`,
		},
		ffmpegGuide: {
			checkingTitle: '正在检测 FFmpeg',
			checkingText: '正在读取安装包内置的 FFmpeg，请稍候。',
			missingTitle: 'FFmpeg 依赖缺失',
			missingTip: '请按以下步骤解决问题：',
			stepDownload: '在 FFmpeg 官网下载适用于',
			stepWindowsPath: '选择一：将 ffmpeg 可执行文件所在路径放至于环境变量中',
			stepUnixPath: '选择一：将 ffmpeg 可执行文件放入 /usr/local/bin',
			stepSameDir: '选择二：将 ffmpeg 可执行文件放入 Komorebi 可执行程序相同目录',
			stepMacDir: (path) => `选择二：将 ffmpeg 可执行文件放入 ${path}`,
			restart: (target) => `完成以上操作后，重启${target}即可开始使用`,
			currentOs: '对应操作系统',
		},
		dragDrop: {
			ncmInputs: (prefix, count) => `${prefix}${count} 个 NCM 输入`,
			inputs: (prefix, count, mode) => `${prefix}${count} 个${mode === 'multiInput' ? '输入路径' : '独立任务'}`,
			textPaths: '文本路径',
			createTask: '拖动文件/文件夹/文本至此处创建任务',
			batchTaskMode: '批量添加任务模式',
			multiInputMode: '多输入单任务模式',
			fastStart: '拖入文件即开始',
			status: (enabled) => `状态：${enabled ? '启用' : '不用'}`,
		},
		komorebi: {
			workflows: {
				videoCompress: '视频压缩',
				audioConvert: '音频转换',
				remux: '转封装',
				ncm: 'NCM转换',
			},
			hints: {
				noInput: '选择或拖入文件后，Komorebi 会自动识别可用格式。',
				hasVideoAudio: '已识别到视频和音频流，不兼容的格式已置灰。',
				hasVideo: '已识别到视频流，不适合音频转换的选项已置灰。',
				hasAudio: '已识别到音频流，不适合视频封装的选项已置灰。',
				unknown: '暂未识别到可转换媒体流。',
			},
			fields: {
				scene: '场景',
				encoder: '编码器',
				quality: '质量',
				container: '封装',
				aspectRatio: '画面比例',
				resolution: '输出分辨率',
				frameRate: '输出帧率',
				gifFps: 'GIF 帧率',
				encodeSpeed: '转换速度',
				audioTrack: '音轨',
				externalAudio: '外部音轨',
				externalAudioFile: '外部音轨文件',
				outputDir: '输出目录',
				outputName: '输出文件名',
				targetFormat: '目标格式',
				targetContainer: '目标容器',
				qualityPreset: '质量档位',
				convertFormat: '转换格式',
			},
			options: {
				sceneAnime: '动画/二次元',
				sceneScreen: '录屏/游戏',
				sceneLive: '摄影',
				qualityHigh: '高质量',
				qualityBalanced: '均衡',
				qualitySmall: '小体积',
				qualityTiny: '极小体积',
				aspectSource: '原始比例',
				aspectStandard: '标准',
				resolutionSource: '原始分辨率',
				resolutionAboveSource: (resolution: string) => `高于源分辨率 ${resolution}`,
				resolutionReadingSource: '正在读取原始分辨率',
				frameRateSource: '原始帧率',
				frameRateAuto: '自动',
				frameRateLimited: (fps: number) => `实际 ${fps} FPS`,
				frameRateAboveSource: (fps: string) => `高于源帧率 ${fps} FPS`,
				gifFpsAuto: '自动',
				gifFpsLimited: (fps: number) => `实际 ${fps} FPS`,
				encodeSpeedFast: '快速',
				encodeSpeedBalanced: '均衡',
				encodeSpeedLow: '低占用',
				keepSourceAudio: '保留源音轨',
				muteVideo: '无声视频',
				useExternalAudio: '使用外部音轨',
				noExternalAudio: '不添加外部音轨',
				addExternalAudio: '添加外部音轨',
				audioLossless320: '320k / 无损',
				audio192: '192k',
				audio128: '128k',
				audio64: '64k',
				ncmAuto: '按源音乐自动输出',
				ncmCopy: '只解密，不压缩',
				ncmStandard: '标准压缩',
				ncmSmall: '小体积压缩',
				recursive: '递归目录',
				deleteSource: '转换成功后删除源文件',
			},
			placeholders: {
				externalAudio: 'C:/Music/audio.flac',
				outputToSourceDir: '留空时输出到源文件目录',
				outputToSourceRoot: '留空时输出到源目录',
				videoOutputName: '留空默认：[filename]_komorebi',
				audioOutputName: '留空默认：[filename]_audio',
				remuxOutputName: '留空默认：[filename]_remux',
				ncmOutputName: '留空使用 ncmdump 默认文件名',
			},
			estimate: {
				waiting: '选中视频任务后显示预计输出大小和压缩率',
				unknown: '当前任务缺少时长或码率信息，暂时无法估算压缩率',
				summary: (output, source, ratioText) => `预计输出 ${output}，源文件约 ${source}，${ratioText}`,
				actualSummary: (output, source, ratioText) => `实际输出 ${output}，源文件 ${source}，${ratioText}`,
				shrink: (rate) => `压缩率约 ${rate}%`,
				grow: (rate) => `预计增大 ${rate}%`,
				flat: '体积基本持平',
				actualShrink: (rate) => `实际压缩率 ${rate}%`,
				actualGrow: (rate) => `实际增大 ${rate}%`,
				actualFlat: '体积基本持平',
			},
			notes: {
				remux: '默认流复制，保留字幕和元数据；容器不兼容时会自动切换到高保真转码重试。',
				ncm: '将 .ncm 文件或文件夹拖入上方任务区；文件夹会展开为单个 NCM 任务。',
			},
			actions: {
				choose: '选择',
				setGlobal: '设为全局参数',
				applySelected: '应用到选中任务',
			},
		},
		applicationMenu: {
			编辑: '编辑',
			撤销: '撤销',
			重做: '重做',
			剪切: '剪切',
			复制: '复制',
			粘贴: '粘贴',
			删除: '删除',
			全选: '全选',
		},
	},
}

export default lang;
